### ISSUE TITLE
Error after a fresh install 

### ISSUE THREAD

**Issue by scampion** [JoelNiklaus/LEXTREME#7]
After a fresh setup I got that error if I run `python3 main.py`

```
 File "/home/scampion/src/LEXTREME/main.py", line 135, in <module>
    run_experiment(
  File "/home/scampion/src/LEXTREME/utils/utilities.py", line 872, in run_experiment
    for lang in list_of_languages:
TypeError: 'NoneType' object is not iterable
```

**Comment by JoelNiklaus** [comment]
Hi Sebastien,

Thanks for using LEXTREME!

Could you try running it like this?
```
python3 main.py -lol all
```

**Comment by scampion** [comment]
Thanks I hacked the source to avoid the error and got the same output that with `python3 main.py -lol all` 

this one, If useful 
```
The language model all will be considered a monolingual model. Therefore, we revert to the default batch size.
LANGUAGE IS:  all
all
Traceback (most recent call last):
  File "/home/scampion/src/LEXTREME/main.py", line 135, in <module>
    run_experiment(
  File "/home/scampion/src/LEXTREME/utils/utilities.py", line 878, in run_experiment
    epoch_and_strategies = get_default_number_of_training_epochs(task=task, model_name=model_name,
  File "/home/scampion/src/LEXTREME/utils/utilities.py", line 371, in get_default_number_of_training_epochs
    if meta_infos["model_language_lookup_table"][model_name] == "all":
KeyError: 'all'
```

**Comment by kapllan** [comment]
Hi @scampion ,
I will check everything and make sure that the documentation is up-to-date. I am sorry for this bug. I will come back to you as soon as possible.

**Comment by scampion** [comment]
If it can help, my latest try, after an update of the metadata to add the model, was :
 
`python main.py -lol en -lmt  EuropeanParliament/EUBERT -t multi_eurlex_level_1`

```
[WARNING|modeling_utils.py:4187] 2023-12-22 15:41:51,075 >> Some weights of HierRobertaForSequenceClassification were not initialized from the model checkpoint
 at EuropeanParliament/EUBERT and are newly initialized: ['classifier.out_proj.bias', 'classifier.dense.bias', 'classifier.out_proj.weight', 'classifier.dense.
weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
[WARNING|logging.py:314] 2023-12-22 15:41:51,259 >> Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned o
r trained.
Running tokenizer on train dataset:   0%|                                                                                     | 0/55000 [00:01<?, ? examples/s]
Traceback (most recent call last):
  File "/home/scampion/src/LEXTREME/./experiments/template_MLTC.py", line 272, in <module>
    main()
  File "/home/scampion/src/LEXTREME/./experiments/template_MLTC.py", line 153, in main
    train_dataset = train_dataset.map(
  File "/home/scampion/src/LEXTREME/venv/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 591, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/scampion/src/LEXTREME/venv/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 556, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/scampion/src/LEXTREME/venv/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 3089, in map
    for rank, done, content in Dataset._map_single(**dataset_kwargs):
  File "/home/scampion/src/LEXTREME/venv/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 3466, in _map_single
    batch = apply_function_on_filtered_inputs(
  File "/home/scampion/src/LEXTREME/venv/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 3345, in apply_function_on_filtered_inputs
    processed_inputs = function(*fn_args, *additional_args, **fn_kwargs)
  File "/home/scampion/src/LEXTREME/./experiments/template_MLTC.py", line 154, in <lambda>
    lambda x: preprocess_function(x, tokenizer, model_args, data_args, id2label=id2label),
  File "/home/scampion/src/LEXTREME/experiments/helper.py", line 406, in preprocess_function
    string_blocks = [tokenizer.convert_tokens_to_string(
  File "/home/scampion/src/LEXTREME/experiments/helper.py", line 406, in <listcomp>
    string_blocks = [tokenizer.convert_tokens_to_string(
  File "/home/scampion/src/LEXTREME/venv/lib/python3.10/site-packages/transformers/tokenization_utils_fast.py", line 612, in convert_tokens_to_string
    return self.backend_tokenizer.decoder.decode(tokens)
AttributeError: 'NoneType' object has no attribute 'decode'
```

**Comment by kapllan** [comment]
Hi @scampion ,

The code had undergone some changes, and it seems like we forgot to update the documentation accordingly. I checked everything and found some bugs which I fixed, and I also updated the documentation.  

First, please, pull the new updates and create a new virtual environment and follow the installation instructions in the README.

During my tests, I also found that another step is required for your model. It belongs to the language models that requires the flag add_prefix_space=True when initializing the tokenizer. This is usually required when using Roberta-based models for token classification tasks. I made the changes in the code, so no further steps are required from your side.

I tested your model with non-hierarchical text classification tasks and token classification tasks, and it works in my virtual environment. However, when trying to run your model with hierarchical text classification tasks, I encountered another issue and I believe it has something to do with your model and not with our implementation. When using the AutoTokenizer from the transformers library, I get this error with your model:

`
File ~/anaconda3/envs/Lextreme/lib/python3.11/site-packages/transformers/tokenization_utils_fast.py:612, in PreTrainedTokenizerFast.convert_tokens_to_string(self, tokens)    611 def convert_tokens_to_string(self, tokens: List[str]) -> str: --> 612     return self.backend_tokenizer.decoder.decode(tokens)  AttributeError: 'NoneType' object has no attribute 'decode'  
`
In order for our code to work, this method needs to be working `tokenizer.convert_tokens_to_string`. Can you please check if this method works with your model’s tokenizer?

**Comment by kapllan** [comment]
Since we did not receive any response, I am closing this issue.
